name = "OneVision"
uuid = "f237c6c4-064b-4cc0-8939-eac982d56a72"
authors = ["Jiayi Wei <wjydzh1@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
