pkg_list = [
    :BenchmarkTools,
    :StaticArrays,
    # :JuMP,
    # :OSQP,
    # :MutableArithmetics,
    :Plots,
    :PlotlyJS,
    :Measures,
    :QuadGK,
    :Unrolled,
    :Setfield,
    :Optim,
    :Traceur,
    :Makie,
    :GLMakie,
]